"""Fleet identity table — JSON file persistence + config generation."""

import json
import os
import subprocess
from pathlib import Path
from typing import Optional

FLEET_FILE = Path("/etc/roban-swarm/fleet.json")
DNSMASQ_FLEET = Path("/etc/dnsmasq.d/roban-swarm-fleet.conf")
MAVLINK_HUB_CONF = Path("/etc/mavlink-router/main.conf")

# For development / non-root testing, fall back to local paths
if not FLEET_FILE.parent.exists():
    FLEET_FILE = Path("data/fleet.json")
    FLEET_FILE.parent.mkdir(parents=True, exist_ok=True)


def _compute_fields(heli_id: int) -> dict:
    return {
        "ip": f"192.168.50.{100 + heli_id}",
        "sysid": 10 + heli_id,
        "hub_port": 14559 + heli_id,
    }


class FleetStore:
    """Thread-safe fleet identity store backed by a JSON file."""

    def __init__(self):
        self._helis: dict[int, dict] = {}
        self._load()

    def _load(self):
        if FLEET_FILE.exists():
            try:
                data = json.loads(FLEET_FILE.read_text())
                self._helis = {int(k): v for k, v in data.items()}
            except (json.JSONDecodeError, KeyError):
                self._helis = {}

    def _save(self):
        FLEET_FILE.parent.mkdir(parents=True, exist_ok=True)
        FLEET_FILE.write_text(json.dumps(self._helis, indent=2))

    def _to_out(self, heli_id: int, h: dict) -> dict:
        computed = _compute_fields(heli_id)
        return {
            "id": heli_id,
            "mac": h["mac"],
            "name": h.get("name", f"Heli{heli_id:02d}"),
            "ip": computed["ip"],
            "sysid": computed["sysid"],
            "hub_port": computed["hub_port"],
            "status": "unknown",
        }

    def list_all(self) -> list[dict]:
        return [self._to_out(k, v) for k, v in sorted(self._helis.items())]

    def get(self, heli_id: int) -> Optional[dict]:
        if heli_id not in self._helis:
            return None
        return self._to_out(heli_id, self._helis[heli_id])

    def add(self, heli_id: int, mac: str, name: Optional[str] = None) -> dict:
        if heli_id in self._helis:
            raise ValueError(f"Heli {heli_id} already exists")
        h = {"mac": mac.lower()}
        if name:
            h["name"] = name
        self._helis[heli_id] = h
        self._save()
        return self._to_out(heli_id, h)

    def update(self, heli_id: int, mac: Optional[str] = None,
               name: Optional[str] = None) -> Optional[dict]:
        if heli_id not in self._helis:
            return None
        if mac is not None:
            self._helis[heli_id]["mac"] = mac.lower()
        if name is not None:
            self._helis[heli_id]["name"] = name
        self._save()
        return self._to_out(heli_id, self._helis[heli_id])

    def delete(self, heli_id: int) -> bool:
        if heli_id not in self._helis:
            return False
        del self._helis[heli_id]
        self._save()
        return True

    def apply_configs(self) -> dict:
        """Regenerate dnsmasq + mavlink-hub configs from fleet table."""
        results = {}

        # --- dnsmasq fleet reservations ---
        lines = [
            "# Auto-generated by roban-controller — do not edit manually",
        ]
        for heli_id, h in sorted(self._helis.items()):
            f = _compute_fields(heli_id)
            name = h.get("name", f"heli{heli_id:02d}")
            lines.append(
                f"dhcp-host={h['mac']},{f['ip']},{name}"
            )
        try:
            DNSMASQ_FLEET.write_text("\n".join(lines) + "\n")
            subprocess.run(["systemctl", "reload", "dnsmasq"],
                           capture_output=True, timeout=10)
            results["dnsmasq"] = "ok"
        except Exception as e:
            results["dnsmasq"] = str(e)

        # --- mavlink-hub config ---
        hub_lines = [
            "# Auto-generated by roban-controller — do not edit manually",
            "",
            "[General]",
            "TcpServerPort = 5760",
            "ReportStats = false",
            "MavlinkDialect = ardupilotmega",
            "",
            "# GCS endpoint",
            "[UdpEndpoint gcs]",
            "Mode = Normal",
            "Address = 0.0.0.0",
            "Port = 14550",
            "",
        ]
        for heli_id in sorted(self._helis.keys()):
            f = _compute_fields(heli_id)
            name = f"heli{heli_id:02d}"
            hub_lines.extend([
                f"[UdpEndpoint {name}]",
                "Mode = Server",
                "Address = 0.0.0.0",
                f"Port = {f['hub_port']}",
                "",
            ])
        try:
            MAVLINK_HUB_CONF.write_text("\n".join(hub_lines))
            subprocess.run(["systemctl", "restart", "mavlink-hub"],
                           capture_output=True, timeout=10)
            results["mavlink_hub"] = "ok"
        except Exception as e:
            results["mavlink_hub"] = str(e)

        return results


# Singleton
fleet_store = FleetStore()
